### ISSUE TITLE
Thermal Heat Rejection dialog missing MKS 'Ranger' Thermal Control System parts

### ISSUE THREAD

**Issue by maddavo** [post-kerbin-mining-corporation/NearFutureElectrical#121]
The MKS 'Ranger' Thermal Control System parts are radiator parts from the MKS/USI mod.  They work OK in dissipating heat from NFE controlled reactors.  But they do not appear in the THERMAL tab of the Near Future Systems Manager.  The Heat Flow calc does not include their dissipation and they do not appear under the Total Heat Rejection number nor the list below when expanded.

Don't know if this is an issue with NFE or MKS.

**Comment by ChrisAdderley** [comment]
This is a Dynamic Battery Storage issue.

This is a special type of radiator that MKS provides. It seems like it is supposed to do cool things, like change heat radiation depending on day/night parameters or landed state, but right now it does... nothing special compared to a normal radiator. However, looking at the code it's just a shockingly overpowered radiator right now (3 MW capacity for 0.15 tons). 

I can support this in a patch going forward, though, it's not hard.. but it's not going to be high priority. See https://github.com/ChrisAdderley/DynamicBatteryStorage/issues/60

**Comment by ChrisAdderley** [comment]
Closing, track progress in linked issue above.
