### ISSUE TITLE
MKS converter name are ModuleResourceConverter, not USI_Converter

### ISSUE THREAD

**Issue by ttr** [post-kerbin-mining-corporation/NearFutureElectrical#129]
Re #122 
Reactors / converters in USI / MKS are still named ModuleResourceConverter -> https://github.com/UmbraSpaceIndustries/MKS/tree/master/FOR_RELEASE/GameData/UmbraSpaceIndustries/ReactorPack/Parts

reverting #122 does fix issue with massive heat generation and two reactors present on MKS parts.

**Comment by ChrisAdderley** [comment]
Reverted in last release
