### ISSUE TITLE
RTG half-life doesn't account for modded day/year lengths

### ISSUE THREAD

**Issue by LouisB3** [post-kerbin-mining-corporation/NearFutureElectrical#133]
If I am reading this correctly, CalculateDecimalYears only works in calendars that are 24h days/365d years or 6h days/426d years. This means that mods that use Kronometer/Kopernicus to produce different day/year lengths will have the half-life of decaying RTGs calculated incorrectly. (E.g. JNSQ uses a 12h day/365d year)

https://github.com/post-kerbin-mining-corporation/NearFutureElectrical/blob/d0a20f2a6e3d0c43659d15d645841da8e8b808fd/Source/NearFutureElectrical/Utils.cs#L115

https://github.com/post-kerbin-mining-corporation/NearFutureElectrical/blob/d0a20f2a6e3d0c43659d15d645841da8e8b808fd/Source/NearFutureElectrical/RadioisotopeGenerator.cs#L80

Related reading referring to other mods which account for different calendars (KAC, Transfer Window Planner, Snacks): https://github.com/Angel-125/Snacks/pull/5

**Comment by LouisB3** [comment]
Confirmed in testing: a custom RTG with a half-life of 1 year operates at 50% efficiency after 213 twelve-hour days in JNSQ (426 stock-length days, or one stock year), instead of 365 days (1 JNSQ year) as expected.

![Screenshot 2021-01-08 15 31 06](https://user-images.githubusercontent.com/9939641/104061601-e73f6c80-51c6-11eb-865a-1ac0d0c7f69a.png)

```
+PART[rtg]:AFTER[NearFutureElectrical]
{
	@name = rtg-test
	@title = test rtg
	@cost *= 0.1
	!MODULE[ModuleGenerator] {}
  %MODULE[ModuleRadioisotopeGenerator]
	{
		%BasePower = 0.75
		%HalfLife = 1
		%EasyMode = false
	}
}
```

**Comment by ChrisAdderley** [comment]
Well... That's kinda expected. The decay rate is based on number of seconds elapsed, not days. If I understand your test case right, the time elapsed is the same.

Changing this would make half life proportional to the day length which is probably not desirable. Instead, the reporting should be adjusted so that the UIs correctly report that remaining time. It would be up to the planet pack author to scale the half life if it needed to be longer.

**Comment by LouisB3** [comment]
I think I see what you are saying... realistically, isotope decay occurs at the same rate irrespective of the local calendar. So we would expect that it would be defined (or described, if you prefer) in time units that do not vary based on the specifics of the solar system. 

However, the behavior you describe 

> half life proportional to the day length which is probably not desirable

is already present, with the two calendars that stock KSP supports. Half-life is defined in years in the config, and output decays based on whether a year is stock "Kerbin time" or "Earth time", as set in the stock settings menu.

Here's a craft (in stock KSP + NFE, no solar system mods) which has been in flight for 24h * 365d. The KSP calendar is set to Earth time: 

![Screenshot 2021-01-14 11 49 22](https://user-images.githubusercontent.com/9939641/104623378-4f2b0280-5660-11eb-8aaf-ce7069266f0f.png)

And here's the same craft with the same flight duration; the only change is setting the calendar to Kerbin time:

![Screenshot 2021-01-14 11 50 37](https://user-images.githubusercontent.com/9939641/104623480-6964e080-5660-11eb-8238-6712b5a2ab93.png)

You can see that NFE is calculating power output based on a half-life defined in years, but since the definition of a year has changed, the power output is different even though the time elapsed is the same in seconds.

So depending on the preferred behavior, there are two possible solutions:

- Change the code to calculate time elapsed in seconds rather than years. Define the unit for the cfg HalfLife value to be "stock Kerbin years" (6h * 426d = 9201600s). Adjust the in-game displayed half-life to match (either report in seconds, or scale up to whatever year length the game is currently using). 
- Change the code to calculate time elapsed based on local years.

**Comment by ChrisAdderley** [comment]
Yes, what I'm describing refers to option 1 there, and yes it would require changes to that method there.

**Comment by ChrisAdderley** [comment]
This should be implemented in the latest version but testing has been limited.
