### ISSUE TITLE
NullReferenceException when loading Reactor-0625

### ISSUE THREAD

**Issue by WilloIzCitron** [post-kerbin-mining-corporation/NearFutureElectrical#146]
Logs:
```
[EXC 10:26:52.415] NullReferenceException: Object reference not set to an instance of an object
	SystemHeat.ModuleSystemHeatFissionReactor.GetInfo () (at <faa8f438e27f4148b7041ce82be5b9c9>:0)
	PartLoader.CompilePartInfo (AvailablePart newPartInfo, Part part) (at <a1ca58b5ca7140639de29a81de5e3f32>:0)
	PartLoader+<CompileParts>d__56.MoveNext () (at <a1ca58b5ca7140639de29a81de5e3f32>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Full Logs:
[KSP.log](https://github.com/post-kerbin-mining-corporation/NearFutureElectrical/files/7832534/KSP.log)
Mods:
Real Solar System
Realism Overhaul
 etc
 
 Reproduce:
 Start KSP with RSS/RO
 Press Alt+F12

**Comment by drCosmar** [comment]
> Logs:
> 
> ```
> [EXC 10:26:52.415] NullReferenceException: Object reference not set to an instance of an object
> 	SystemHeat.ModuleSystemHeatFissionReactor.GetInfo () (at <faa8f438e27f4148b7041ce82be5b9c9>:0)
> 	PartLoader.CompilePartInfo (AvailablePart newPartInfo, Part part) (at <a1ca58b5ca7140639de29a81de5e3f32>:0)
> 	PartLoader+<CompileParts>d__56.MoveNext () (at <a1ca58b5ca7140639de29a81de5e3f32>:0)
> 	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
> 	UnityEngine.DebugLogHandler:LogException(Exception, Object)
> 	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
> 	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
> ```
> 
> Full Logs: [KSP.log](https://github.com/post-kerbin-mining-corporation/NearFutureElectrical/files/7832534/KSP.log) Mods: Real Solar System Realism Overhaul etc
> 
> Reproduce: Start KSP with RSS/RO Press Alt+F12

That looks to be more like an issue with System Heat rather than NFE.

**Comment by ChrisAdderley** [comment]
I can't support RO installs due to the extreme complexity.
