### ISSUE TITLE
Fission reactors don't integrate with System Heat 

### ISSUE THREAD

**Issue by t968rs** [post-kerbin-mining-corporation/NearFutureElectrical#148]
Fission reactors are missing the IVP item for selecting the "Loop ID." Thus, it is not possible to select a target temperature for a radiator loop that matches the reactor. I also have Far Future. The Fusion reactors work as expected.
![image](https://user-images.githubusercontent.com/19416421/198359387-e6717902-9572-4ce1-a6e2-5f36867c53d7.png)

**Comment by ChrisAdderley** [comment]
You need to install the appropriate integration patch.
