### ISSUE TITLE
Error with B9PS and NFE - Size0Radiators

### ISSUE THREAD

**Issue by etmoonshade** [post-kerbin-mining-corporation/NearFutureElectrical#158]
Caught this error after installing the newest update from CKAN:
![image](https://github.com/user-attachments/assets/c31fbd3d-e688-4b75-b95f-3cc46b7084f3)

KSP.log snippet:
[LOG 17:59:56.379] PartLoader: Compiling Part 'NearFutureElectrical/Parts/FissionReactors/nfe-reactor-tiny-1/nfe-reactor-tiny-1'
[ERR 17:59:56.382] Cannot find a PartModule of typename 'ModuleSystemHeat'
[ERR 17:59:56.383] Cannot find a PartModule of typename 'ModuleSystemHeatFissionReactor'
[ERR 17:59:56.383] Cannot find a PartModule of typename 'ModuleSystemHeatFissionFuelContainer'
[LOG 17:59:56.391] PartLoader: Part 'NearFutureElectrical/Parts/FissionReactors/nfe-reactor-tiny-1/nfe-reactor-tiny-1' has no database record. Creating.
[LOG 17:59:56.391] [DragCubeSystem]: Drag cubes not found or cannot be read for part PartTapIn. Generating New drag cubes.
[LOG 17:59:56.391] [KSPCF/DragCubeGeneration] Creating drag cubes for part 'nfe-reactor-tiny-1'
[WRN 17:59:56.400] Warning on PartSubtype Size0Radiators on module ModuleB9PartSwitch (moduleID='meshSwitch') on part nfe-reactor-tiny-1: Could not find matching module
[EXC 17:59:56.400] Exception: Could not find matching module
	B9PartSwitch.ModuleMatcher.FindModule (Part part) (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	B9PartSwitch.ModuleModifierInfo+<CreatePartModifiers>d__10.MoveNext () (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	B9PartSwitch.PartSubtype.Setup (B9PartSwitch.ModuleB9PartSwitch parent, System.Boolean displayWarnings) (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	B9PartSwitch.PartSubtype:Setup(ModuleB9PartSwitch, Boolean)
	B9PartSwitch.ModuleB9PartSwitch:InitializeSubtypes(Boolean)
	B9PartSwitch.ModuleB9PartSwitch:GetInfo()
	PartLoader:CompilePartInfo(AvailablePart, Part)
	<CompileParts>d__56:PartLoader+<CompileParts>d__56.MoveNext_Patch0(<CompileParts>d__56)
	KSPCommunityFixes.Performance.<FrameUnlockedCoroutine>d__63:MoveNext()
	KSPCommunityFixes.Performance.<PartLoader_CompileAll>d__59:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

Let me know if you need the full KSP.log - I'm definitely running a lot of mods.

**Comment by ChrisAdderley** [comment]
I forgot to update the CKAN listing to add the new dependency (SystemHeat). Do you have that?

**Comment by etmoonshade** [comment]
I do not - if CKAN isn't updated by the time I finish the mission I'm in the middle of, I'll grab it and see if it makes the error go away.

**Comment by etmoonshade** [comment]
Okay, look, that was a REALLY long trip back from Urium...

Installing SystemHeat indeed made the error go away.

**Comment by ChrisAdderley** [comment]
Cool, good stuff. I've updated the CKAN dependencies as well.

**Comment by etmoonshade** [comment]
@ChrisAdderley - not going to reopen, but since it might be a mistake with the update...
![image](https://github.com/user-attachments/assets/cf98f3ee-60dd-45f9-a1c0-747a4e63f7aa)

Looks like you might have the wrong package names in CKAN for SystemHeat?
